'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const root=path.join(__dirname,'..');
function load(files=['range-core.js','flow-policy.js','cdn-resolver.js','idm-downloader.js'],extra={}){
 const ctx=vm.createContext({console,URL,Headers,Response,Request,AbortController,DOMException,Uint8Array,ArrayBuffer,performance,setTimeout,clearTimeout,WeakRef,location:{href:'https://www.bilibili.com/video/BV1fixture',origin:'https://www.bilibili.com'},...extra});
 for(const f of files)vm.runInContext(fs.readFileSync(path.join(root,'src',f),'utf8'),ctx,{filename:f});return ctx;
}
const c=load(),range=c.__BILI_RANGE_CORE__,policy=c.__BTR_FLOW_POLICY__,cdn=c.__BILI_CDN_RESOLVER_FACTORY__;
const home=require('../src/home-core.js');
function resolver(urls=['https://a.bilivideo.com/v.m4s']){
 const failures=[];return{failures,urls:()=>urls,ordered:()=>urls,rangeCandidates:()=>urls,startupCandidates:()=>urls,rescueCandidates:()=>urls,allows:()=>true,speed:()=>0,sample(){},success(){},failure(u,e,b){failures.push({u,e,b});}};
}
function requestRange(init){return range.parseRangeHeader(new Headers(init.headers).get('range'));}
function response(r,total=1024*1024,extra={}){return new Response(new Uint8Array(r.length).map((_,i)=>(r.start+i)%251),{status:206,headers:{'content-range':`bytes ${r.start}-${r.end}/${total}`,'content-length':String(r.length),...extra}});}
function makeDownload(ctx,fetch,settings={}){return ctx.__BILI_IDM_DOWNLOADER_FACTORY__.createDownloader({nativeFetch:fetch,getSettings:()=>({autoConcurrency:false,concurrency:8,smartPolicy:false,...settings})});}

test('strict closed byte ranges',()=>{assert.equal(range.parseRangeHeader('bytes=0-0').length,1);for(const s of ['bytes=-10','bytes=1-','bytes=9-2','bytes=1-2,4-5'])assert.equal(range.parseRangeHeader(s),null);});
test('content-range total must exceed end',()=>{assert.equal(range.parseContentRange('bytes 0-2/2'),null);assert.equal(range.parseContentRange('bytes 0-2/3').total,3);});
test('split range covers exactly once for many sizes',()=>{for(let n=1;n<900000;n+=17389){const a=range.splitRange(19,18+n,32);assert.equal(a[0].start,19);assert.equal(a.at(-1).end,18+n);assert.equal(a.reduce((s,p)=>s+p.length,0),n);for(let i=1;i<a.length;i++)assert.equal(a[i].start,a[i-1].end+1);}});
test('concat rejects overflow and truncation',()=>{assert.throws(()=>range.concatChunks([new Uint8Array(5)],4));assert.throws(()=>range.concatChunks([new Uint8Array(2)],4));});
test('CDN hostname boundary and HTTPS validation',()=>{assert.equal(range.isBilibiliMediaUrl('https://bilivideo.com.evil.test/a.m4s'),false);assert.equal(range.isBilibiliMediaUrl('http://a.bilivideo.com/a.m4s'),false);assert.equal(range.isBilibiliMediaUrl('https://a.bilivideo.com/a.m4s'),true);});
test('auto routes retain real original URL and explore both regions',()=>{const rep={baseUrl:'https://original.bilivideo.com/v.m4s?a=1',backupUrl:['https://upos-hz-mirrorakam.akamaized.net/v.m4s?a=1']};const urls=cdn.representationUrls(rep,'auto');assert(urls.includes(rep.baseUrl));assert(urls.includes(rep.backupUrl[0]));assert(urls.some(x=>x.includes('mirrorali.bilivideo')));assert(urls.some(x=>x.includes('mirroraliov.bilivideo')));});
test('custom routes stay within selected hosts',()=>{const urls=cdn.representationUrls({baseUrl:'https://a.bilivideo.com/v.m4s'},'custom',['upos-sz-mirrorali.bilivideo.com']);assert(urls.every(u=>new URL(u).host==='upos-sz-mirrorali.bilivideo.com'));});
test('429 is cooldown, not permanent ban',()=>{let bans=0;const r=cdn.createResolver({baseUrl:'https://a.bilivideo.com/v.m4s'},()=> 'auto',{allows:()=>true,record(){bans++;},success(){}});const u=r.urls()[0];r.failure(u,{status:429,retryAfterMs:12000});assert.equal(bans,0);assert(r.retryAfter(u)>11000);});
test('policy differentiates short videos and high bitrate',()=>{const a=policy.compute({}, {duration:90,bitrate:1000000}),b=policy.compute({}, {duration:500,height:2160,bitrate:15000000});assert.equal(a.cap,8);assert.equal(b.cap,32);assert(a.ahead<b.ahead);});
test('2x playback increases media-seconds buffer within cap',()=>{const a=policy.compute({}, {duration:600,rate:1,bitrate:2000000}),b=policy.compute({}, {duration:600,rate:2,bitrate:2000000});assert.equal(b.ahead,a.ahead*2);});
test('high bitrate buffer obeys estimated memory budget',()=>{const p=policy.compute({memoryBudgetMB:32},{bitrate:25000000,height:2160,duration:600});assert(p.ahead<=9);});
test('economy uses four threads and narrow prefetch window',()=>{const p=policy.compute({strategy:'economy'},{duration:600,height:2160});assert.equal(p.cap,4);assert.equal(p.window,1);assert.equal(p.ahead,12);});
test('hidden paused throttles, hidden playing does not',()=>{assert.equal(policy.compute({}, {hidden:true,paused:true}).cap,4);assert.equal(policy.compute({}, {hidden:true,paused:false}).cap,16);});
test('explicit automatic hard cap honored',()=>{assert.equal(policy.compute({maxAutoThreads:8},{height:2160}).cap,8);});
test('fast-start max buffer is bounded',()=>{assert.equal(policy.compute({strategy:'fast'},{}).startupMax,4);});
test('decode warning requires buffer, not just frame drops',()=>{assert.equal(policy.compute({}, {droppedRatio:.1,ahead:10}).decodeWarning,true);assert.equal(policy.compute({}, {droppedRatio:.1,ahead:0}).decodeWarning,false);});
test('adaptive policy can be disabled',()=>{assert.equal(range.normalizeSettings({smartPolicy:false}).bufferAheadSeconds,45);});
test('default CDN and settings are auto',()=>{assert.equal(range.normalizeSettings({}).mode,'auto');assert.equal(range.normalizeSettings({}).strategy,'auto');});
test('history strips query/tracking and rejects foreign video URLs',()=>{const a=home.card({url:'https://www.bilibili.com/video/BV1test?p=9&token=SECRET',title:'t'});assert.equal(a.url,'https://www.bilibili.com/video/BV1test');assert.equal(home.card({url:'javascript:alert(1)',title:'x'}),null);assert.equal(home.card({url:'https://evil.test/video/BV1test',title:'x'}),null);});
test('history rejects foreign cover and keeps titles as text',()=>{const a=home.card({url:'/video/BV1test',title:'<script>x</script>',image:'https://evil.test/x.jpg'});assert.equal(a.image,'');assert.equal(a.title,'<script>x</script>');});
function batch(n){return[1,2,3].map(i=>({url:`/video/BV${n}item${i}`,title:`视频${n}-${i}`}));}
test('history dedupes same batch',()=>{let h=home.append([],batch(1));h=home.append(h,batch(1));assert.equal(h.length,1);});
test('history bounded to 25 and 7 days',()=>{let h=[];for(let n=0;n<30;n++)h=home.append(h,batch(n));assert.equal(h.length,25);assert.equal(home.history(h,Date.now()+8*86400000).length,0);});
test('history dedupes duplicate cards',()=>{assert.equal(home.cards([batch(1)[0],batch(1)[0]]).length,1);});
test('manifest asks only for storage: no proxy (Chrome rejects it as optional), no broad host permissions',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json')));assert.deepEqual(m.permissions,['storage']);assert(!m.optional_permissions);assert(!m.host_permissions);});
test('all manifest and HTML local assets exist',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json')));for(const e of m.content_scripts)for(const file of [...(e.js||[]),...(e.css||[])])assert(fs.existsSync(path.join(root,file)),file);for(const file of [m.background.service_worker,m.options_page,m.action.default_popup])assert(fs.existsSync(path.join(root,file)),file);});
test('valid concurrent download reassembles exact bytes',async()=>{const d=makeDownload(load(),async(_u,init)=>response(requestRange(init)));const r=await d.downloadRange({start:0,end:524287,length:524288},resolver());assert.equal(r.bytes.length,524288);for(let i=0;i<r.bytes.length;i+=109)assert.equal(r.bytes[i],i%251);assert(r.pieceCount>1);});
test('wire requests omit cookies and reject pre-aborted task',async()=>{let calls=0;const d=makeDownload(load(),async(_u,init)=>{calls++;assert.equal(init.credentials,'omit');return response(requestRange(init));});const controller=new AbortController();controller.abort();await assert.rejects(d.downloadRange({start:0,end:99,length:100},resolver(),{signal:controller.signal}));assert.equal(calls,0);});
test('bad ranges rejected before network',async()=>{let calls=0;const d=makeDownload(load(),()=>{calls++;});await assert.rejects(d.downloadRange({start:10,end:0,length:-9},resolver()));await assert.rejects(d.downloadRange({start:0,end:200000000,length:200000001},resolver()));assert.equal(calls,0);});
test('mismatched Content-Range is never delivered',async()=>{const r=resolver(),ctl=new AbortController();const d=makeDownload(load(),async()=>new Response(new Uint8Array(10),{status:206,headers:{'content-range':'bytes 1-10/100'}}));const timer=setTimeout(()=>ctl.abort(),80);try{await assert.rejects(d.downloadRange({start:0,end:9,length:10},r,{signal:ctl.signal}));assert(r.failures.some(x=>x.e.message.includes('Range 校验')));}finally{clearTimeout(timer);}});
test('resource total consistency checked before reading wrong body',async()=>{const r=resolver();let count=0,wrongReads=0;const d=makeDownload(load(),async(_u,init)=>{const range=requestRange(init);if(!count++)return response(range,1000);return{status:206,headers:new Headers({'content-range':`bytes ${range.start}-${range.end}/2000`}),get body(){wrongReads++;throw Error('must not read');}};});await d.downloadRange({start:0,end:99,length:100},r);const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),80);try{await assert.rejects(d.downloadRange({start:100,end:199,length:100},r,{signal:ctl.signal}));assert.equal(wrongReads,0);assert(r.failures.some(x=>x.e.message.includes('文件总长度不一致')));}finally{clearTimeout(timer);}});
test('oversize streaming response is canceled rather than accumulated',async()=>{const r=resolver(),ctl=new AbortController();let canceled=0;const d=makeDownload(load(),async(_u,init)=>{const p=requestRange(init);return new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array(p.length+5));},cancel(){canceled++;}}),{status:206,headers:{'content-range':`bytes ${p.start}-${p.end}/10000`}});});const timer=setTimeout(()=>ctl.abort(),100);try{await assert.rejects(d.downloadRange({start:0,end:99,length:100},r,{signal:ctl.signal}));assert(r.failures.some(x=>x.e.message.includes('超过请求范围')));assert(canceled>0);}finally{clearTimeout(timer);} });
test('progressive consumer failure cancels sibling tasks',async()=>{const r=resolver(),events=[];const d=makeDownload(load(),async(_u,init)=>{const p=requestRange(init);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>resolve(response(p,1048576)),p.start===0?5:200);init.signal.addEventListener('abort',()=>{clearTimeout(timer);events.push('abort');reject(init.signal.reason);},{once:true});});});await assert.rejects(d.downloadRange({start:0,end:524287,length:524288},r,{onOrderedChunk(){throw Error('consumer failed');}}),/consumer failed/);await new Promise(r=>setTimeout(r,30));assert(events.length>=2);});
test('automatic concurrency respects economy cap inside downloader',()=>{const x=load();const d=x.__BILI_IDM_DOWNLOADER_FACTORY__.createDownloader({nativeFetch:()=>{},getSettings:()=>({autoConcurrency:true,strategy:'economy'})});assert.equal(d.getConcurrency(),4);});
test('manual thread setting is not overwritten by economy cap',()=>{const d=makeDownload(load(),()=>{}, {concurrency:16,smartPolicy:true,strategy:'economy',autoConcurrency:false});assert.equal(d.getConcurrency(),16);});

test('manual auto cap applies even without smart content policy',()=>{const x=load();const d=x.__BILI_IDM_DOWNLOADER_FACTORY__.createDownloader({nativeFetch:()=>{},getSettings:()=>({autoConcurrency:true,smartPolicy:false,maxAutoThreads:4})});assert.equal(d.getConcurrency(),4);});

test('short 4K videos retain bitrate headroom without a long ahead target',()=>{const p=policy.compute({}, {duration:60,height:2160,bitrate:15000000});assert.equal(p.cap,32);assert(p.ahead<=24);});
test('diagnostic postMessage failure cannot break playback observation',()=>{const x=load(undefined,{postMessage(){throw Error('fixture diagnostic channel failure');}});assert.doesNotThrow(()=>x.__BTR_FLOW_POLICY__.observe({duration:60,playbackRate:1,videoHeight:270,paused:false}, {bandwidth:1000000},{}));});
test('home ad helpers: badge text is exact, API ad items are recognised',()=>{const h=require('../src/home-core.js');
 for(const t of ['广告',' 广告 ','推广','AD'])assert(h.isAdBadge(t),t);for(const t of ['广告人','不是广告','推广曲','','12:34'])assert(!h.isAdBadge(t),t);
 assert(h.isAdItem({goto:'ad'})&&h.isAdItem({goto:'av',is_ad:true})&&h.isAdItem({goto:'av',business_info:{}})&&h.isAdItem({goto:'av',uri:'https://cm.bilibili.com/x'}));
 assert(!h.isAdItem({goto:'av',uri:'https://www.bilibili.com/video/BV1x'}));
 assert(h.AD_SELECTOR.includes('.bili-video-card__stats > .bili-video-card__stats--text'));});
