'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const f=require('../src/feed-core.js'),home=require('../src/home-core.js');
const item=(bvid,x={})=>({goto:'av',bvid,title:'标题 '+bvid,pic:'http://i1.hdslb.com/bfs/archive/abc.jpg',duration:754,pubdate:1759800000,owner:{name:'UP'},stat:{view:123456,danmaku:789},...x});

test('md5 matches node crypto for ASCII, UTF-8 and block boundaries',()=>{for(const s of ['','abc','中文',('x').repeat(55),('y').repeat(56),('z').repeat(64),('w').repeat(1000)])assert.equal(f.md5(s),crypto.createHash('md5').update(s).digest('hex'));});
test('WBI signing reproduces the documented example',()=>{const k={img:'7cd084941338484aae1ad9425b84077c',sub:'4932caff0ff746eab6f01bf08b70ac45'};assert.equal(f.mixinKey(k.img,k.sub),'ea1db124af3c7062474693fa704f4ff8');assert.equal(f.signWbi({foo:'114',bar:'514',zab:1919810},k,1702204169),'bar=514&foo=114&wts=1702204169&zab=1919810&w_rid=8f6f2b5b3d485fe1886cec6a0be8c5d4');});
test('signing strips the characters the web client strips',()=>{const k={img:'7cd084941338484aae1ad9425b84077c',sub:'4932caff0ff746eab6f01bf08b70ac45'};assert.match(f.signWbi({q:"a!b'c(d)e*f"},k,1),/^q=abcdef&wts=1&w_rid=[0-9a-f]{32}$/);});
test('nav response yields keys only when both are 32-hex file names',()=>{assert.deepEqual(f.keysFromNav({data:{wbi_img:{img_url:'https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077c.png',sub_url:'https://i0.hdslb.com/bfs/wbi/4932caff0ff746eab6f01bf08b70ac45.png'}}}),{img:'7cd084941338484aae1ad9425b84077c',sub:'4932caff0ff746eab6f01bf08b70ac45'});assert.equal(f.keysFromNav({data:{}}),null);assert.equal(f.keysFromNav({data:{wbi_img:{img_url:'x/evil.png',sub_url:'y.png'}}}),null);});
test('concurrent lanes use distinct page indices and requested size',()=>{const a=f.rcmdParams(3,24),b=f.rcmdParams(4,24);assert.equal(a.ps,24);assert.notEqual(a.fresh_idx,b.fresh_idx);assert.notEqual(a.brush,b.brush);});
test('cards keep videos only: ads, live, bad ids, untitled and duplicates are dropped',()=>{const seen=new Set(['BV1aaaaaaaaa']);const out=f.cards([item('BV1aaaaaaaaa'),item('BV1bbbbbbbbb'),item('BV1bbbbbbbbb'),item('BV1ccccccccc',{goto:'live'}),item('BV1ddddddddd',{business_info:{id:1}}),item('BV1eeeeeeeee',{goto:'ad'}),item('notabvid'),item('BV1fffffffff',{title:''}),null,item('BV1ggggggggg',{is_followed:1})],seen);
 assert.deepEqual(out.map(c=>c.bvid),['BV1bbbbbbbbb','BV1ggggggggg']);assert(seen.has('BV1ggggggggg'));assert.equal(out[1].followed,true);assert.equal(out[0].url,'https://www.bilibili.com/video/BV1bbbbbbbbb');});
test('covers are forced to https on hdslb and downscaled; foreign hosts rejected',()=>{assert.equal(f.cover('http://i1.hdslb.com/bfs/archive/abc.jpg'),'https://i1.hdslb.com/bfs/archive/abc.jpg@480w_270h_1c.webp');assert.equal(f.cover('//i0.hdslb.com/a.png@100w.webp'),'https://i0.hdslb.com/a.png@480w_270h_1c.webp');assert.equal(f.cover('https://evil.com/a.jpg'),'');assert.equal(f.cover('javascript:alert(1)'),'');});
test('durations, counts and dates read like B 站',()=>{assert.equal(f.duration(754),'12:34');assert.equal(f.duration(3725),'1:02:05');assert.equal(f.duration(0),'');assert.equal(f.count(999),'999');assert.equal(f.count(123456),'12.3万');assert.equal(f.count(20000),'2万');assert.equal(f.count(150000000),'1.5亿');const now=new Date(2026,9,8,12).getTime();assert.equal(f.date(now/1000-600,now),'10分钟前');assert.equal(f.date(now/1000-7200,now),'2小时前');assert.equal(f.date(new Date(2026,9,5).getTime()/1000,now),'10-5');assert.equal(f.date(new Date(2025,0,2).getTime()/1000,now),'2025-1-2');});
test('risk-control codes pause instead of retrying',()=>{assert.equal(f.classify({code:0}),'ok');assert.equal(f.classify({code:-352}),'risk');assert.equal(f.classify({code:-412}),'risk');assert.equal(f.classify({code:-400}),'error');assert.equal(f.classify(null),'bad');});
test('infinite feed is opt-in and its numbers are clamped',()=>{assert.equal(home.defaults.homeInfinite,false);const s=home.settings({homeInfinite:true,homeInfiniteSize:99,homeInfiniteThreads:9});assert.equal(s.homeInfinite,true);assert.equal(s.homeInfiniteSize,36);assert.equal(home.settings({homeInfiniteSize:30}).homeInfiniteSize,36);assert.equal(home.settings({homeInfiniteSize:20}).homeInfiniteSize,24);assert.equal(home.settings({homeInfiniteSize:5}).homeInfiniteSize,12);assert.equal(s.homeInfiniteThreads,3);assert.equal(home.settings({}).homeInfiniteThreads,2);});
test('manifest loads feed core and infinite module before the home enhancer, no new permissions',()=>{const m=JSON.parse(fs.readFileSync(path.join(__dirname,'../manifest.json'),'utf8'));const e=m.content_scripts.find(c=>c.js.includes('src/home-enhancer.js'));assert.deepEqual(e.js,['src/ui-kit.js','src/home-core.js','src/feed-core.js','src/home-infinite.js','src/home-enhancer.js']);assert.deepEqual(m.permissions,['storage']);assert(!m.host_permissions);});
test('quick panel runs in the top frame of every B 站 page after its cores; welcome page assets exist',()=>{const root=path.join(__dirname,'..');const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));const e=m.content_scripts.find(c=>c.js.includes('src/quick-panel.js'));assert.deepEqual(e.js,['src/ui-kit.js','src/home-core.js','src/focus-core.js','src/quick-panel.js']);assert.deepEqual(e.matches,['https://*.bilibili.com/*']);assert(!e.all_frames);assert.equal(e.world,'ISOLATED');
 const html=fs.readFileSync(path.join(root,'ui/welcome.html'),'utf8');for(const ref of html.matchAll(/(?:src|href)="([^"#:]+)"/g))assert(fs.existsSync(path.join(root,'ui',ref[1])),ref[1]);assert(fs.readFileSync(path.join(root,'src/service-worker.js'),'utf8').includes('ui/welcome.html'));});
test('every ad shape the web feed API uses is skipped; plain videos with ad-ish titles stay',()=>{
 const ads=[item('BV1aaaaaaaa1',{is_ad:true}),item('BV1aaaaaaaa2',{is_ad:1}),item('BV1aaaaaaaa3',{goto:'ad'}),item('BV1aaaaaaaa4',{business_info:{id:7,is_ad:true}}),
  item('BV1aaaaaaaa5',{ad_info:{creative_id:1}}),item('BV1aaaaaaaa6',{uri:'https://cm.bilibili.com/cm/api/fees/pc/sync/v2?x=1'}),item('BV1aaaaaaaa7',{room_info:{room_id:1}}),item('BV1aaaaaaaa8',{goto:'live'})];
 assert.equal(f.cards(ads).length,0);
 const ok=f.cards([item('BV1bbbbbbbb1',{title:'广告人的一天',owner:{name:'推广'},uri:'https://www.bilibili.com/video/BV1bbbbbbbb1',business_info:null,is_ad:false})]);
 assert.equal(ok.length,1);
});
