'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const f=require('../src/focus-core.js');
const T0=new Date(2026,9,8,20,0,0).getTime();
const H=3600000,MIN=60000;
const on=(x={})=>f.settings({focusEnabled:true,focusSessionMinutes:0,focusWeeklyHours:0,...x});
function watch(u,s,seconds,id='BV1aa411c7mD',start=T0){let now=start;for(let i=0;i<seconds;i+=5){now+=5000;u=f.tick(u,now,s,5,id);}return{u,now};}

test('focus mode is off by default and settings are clamped',()=>{const s=f.settings({});assert.equal(s.focusEnabled,false);assert.equal(s.focusWindowMinutes,90);assert.equal(s.focusWeeklyHours,10);const c=f.settings({focusWindowMinutes:999,focusWeeklyHours:-1,focusBreakMinutes:0,focusWindowVideos:'x'});assert.equal(c.focusWindowMinutes,300);assert.equal(c.focusWeeklyHours,0);assert.equal(c.focusBreakMinutes,1);assert.equal(c.focusWindowVideos,0);});
test('disabled focus mode never blocks but still meters',()=>{const s=f.settings({focusWindowMinutes:1});const {u,now}=watch(null,s,120);const e=f.evaluate(u,now,s);assert.equal(e.block,null);assert.equal(e.window.seconds,120);});
test('5-hour window starts at first watched second and reports reset time',()=>{const s=on({focusWindowMinutes:60});const e0=f.evaluate(f.usage(null,T0),T0,s);assert.equal(e0.window.resetAt,0);const {u,now}=watch(null,s,5);const e=f.evaluate(u,now,s);assert.equal(e.window.resetAt,T0+f.WINDOW_MS);assert.equal(e.window.percent,0);assert.equal(f.fmtReset(e.window.resetAt,now),'明天 01:00');});
test('window limit blocks until its reset, then a new window starts',()=>{const s=on({focusWindowMinutes:1});let r=watch(null,s,55);assert.equal(f.evaluate(r.u,r.now,s).block,null);r=watch(r.u,s,5,undefined,r.now);const b=f.evaluate(r.u,r.now,s).block;assert.equal(b.kind,'window');assert.equal(b.resetAt,T0+f.WINDOW_MS);
 const later=T0+f.WINDOW_MS+1000;const u2=f.usage(r.u,later);assert.equal(u2.window.seconds,0);assert.equal(f.evaluate(u2,later,s).block,null);const t=f.tick(u2,later+5000,s,5,'BV1aa411c7mD');assert.equal(t.window.start,later);});
test('weekly allowance spans windows and resets after 7 days',()=>{const s=on({focusWindowMinutes:0,focusWeeklyHours:1});let r=watch(null,s,1800);r=watch(r.u,s,1795,undefined,T0+6*H);assert.equal(f.evaluate(r.u,r.now,s).block,null);assert.equal(r.u.window.seconds,1795,'new 5h window');r=watch(r.u,s,5,undefined,r.now);const b=f.evaluate(r.u,r.now,s).block;assert.equal(b.kind,'week');assert.equal(b.resetAt,T0+f.WEEK_MS);
 const next=f.usage(r.u,T0+f.WEEK_MS+1);assert.equal(next.week.seconds,0);assert.equal(f.evaluate(next,T0+f.WEEK_MS+1,s).block,null);});
test('weekly block wins over window block and percentages are capped',()=>{const s=on({focusWindowMinutes:1,focusWeeklyHours:1});const u={window:{start:T0,seconds:4000},week:{start:T0,seconds:4000}};const e=f.evaluate(f.usage(u,T0+1000),T0+1000,s);assert.equal(e.block.kind,'week');assert.equal(e.window.percent,100);assert.equal(e.remaining,0);});
test('video count per window: current video may finish, new one is blocked',()=>{const s=on({focusWindowMinutes:0,focusWindowVideos:2});let r=watch(null,s,5,'BV1aa411c7mD');assert.equal(r.u.window.videos.length,0);r=watch(r.u,s,10,'BV1aa411c7mD',r.now);assert.equal(r.u.window.videos.length,1);r=watch(r.u,s,15,'BV1bb411c7mD',r.now);assert.equal(f.evaluate(r.u,r.now,s,'BV1bb411c7mD').block,null);assert.equal(f.evaluate(r.u,r.now,s,'BV1cc411c7mD').block.kind,'videos');});
test('pomodoro break starts after a continuous session and ends by itself',()=>{const s=on({focusWindowMinutes:0,focusSessionMinutes:1,focusBreakMinutes:2});const r=watch(null,s,60);assert.equal(f.evaluate(r.u,r.now,s).block.kind,'break');const during=f.tick(r.u,r.now+5000,s,5,'BV1aa411c7mD');assert.equal(during.window.seconds,r.u.window.seconds,'no counting during a break');const t=f.tick(r.u,r.now+121000,s,5,'BV1aa411c7mD');assert.equal(f.evaluate(t,r.now+121000,s).block,null);assert.equal(t.sessionSeconds,5);});
test('a long pause resets the pomodoro session but not the window',()=>{const s=on({focusWindowMinutes:0,focusSessionMinutes:10,focusBreakMinutes:5});const r=watch(null,s,300);const t=f.tick(r.u,r.now+6*MIN,s,5,'BV1aa411c7mD');assert.equal(t.sessionSeconds,5);assert.equal(t.window.seconds,305);});
test('snooze grants five minutes / one video / skips break, never in strict mode',()=>{const s=on({focusWindowMinutes:1});const r=watch(null,s,60);const sn=f.snooze(r.u,r.now,s,'window');const e=f.evaluate(sn,r.now,s);assert.equal(e.block,null);assert.equal(e.window.remaining,300);assert.equal(sn.snoozes,1);const strict={...s,focusStrict:true};assert.equal(f.evaluate(f.snooze(r.u,r.now,strict,'window'),r.now,strict).block.kind,'window');
 const w=on({focusWindowMinutes:0,focusWeeklyHours:1});const rw=watch({week:{start:T0,seconds:3595}},w,5);assert.equal(f.evaluate(rw.u,rw.now,w).block.kind,'week');assert.equal(f.evaluate(f.snooze(rw.u,rw.now,w,'week'),rw.now,w).block,null);
 const b=on({focusWindowMinutes:0,focusSessionMinutes:1});const rb=watch(null,b,60);assert.equal(f.evaluate(f.snooze(rb.u,rb.now,b,'break'),rb.now,b).block,null);});
test('snoozes and extra time expire with their window',()=>{const s=on({focusWindowMinutes:1});const r=watch(null,s,60);const sn=f.snooze(r.u,r.now,s,'window');const later=f.usage(sn,T0+f.WINDOW_MS+1);assert.equal(later.window.extraSeconds,0);assert.equal(later.snoozes,0);});
test('corrupt or future-dated storage is ignored and tick input is bounded',()=>{const s=on();const u=f.tick({window:{start:T0+99*H,seconds:'NaN'},week:'x',breakUntil:T0+999*H},T0,s,9999,'BV1aa411c7mD');assert.equal(u.window.seconds,30);assert.equal(u.window.start,T0-30000);assert.equal(u.breakUntil,0);assert.deepEqual(u.window.videos,['BV1aa411c7mD']);
 const legacy=f.usage({day:'2026-10-08',seconds:500,videos:['a']},T0);assert.equal(legacy.window.seconds,0);assert.equal(legacy.week.seconds,0);});
test('reset and remaining times read like Claude Code',()=>{const now=new Date(2026,9,8,10,0).getTime();assert.equal(f.fmtReset(new Date(2026,9,8,15,20).getTime(),now),'今天 15:20');assert.equal(f.fmtReset(new Date(2026,9,14,21,5).getTime(),now),'10月14日 周三 21:05');assert.equal(f.fmtReset(0,now),'开始观看后计时');assert.equal(f.fmtLeft(83*MIN),'1 小时 23 分');assert.equal(f.fmtLeft(3*86400000+2*H),'3 天 2 小时');assert.equal(f.fmtLeft(10000),'1 分钟');});
test('video ids for normal, multi-part, bangumi and live pages',()=>{assert.equal(f.videoId('https://www.bilibili.com/video/BV1xx411c7mD/?p=2'),'BV1xx411c7mD');assert.equal(f.videoId('https://www.bilibili.com/bangumi/play/ep123'),'ep123');assert.equal(f.videoId('https://live.bilibili.com/21452505?x=1'),'live21452505');assert.equal(f.videoId('https://www.bilibili.com/'),null);assert.equal(f.videoId('https://search.bilibili.com/all?keyword=a'),null);});
test('focus scripts are declared in the manifest and the service worker loads the core',()=>{const root=path.join(__dirname,'..');const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));const e=m.content_scripts.find(c=>c.js.includes('src/focus-guard.js'));assert.deepEqual(e.js,['src/ui-kit.js','src/focus-core.js','src/focus-guard.js']);assert.equal(e.world,'ISOLATED');assert(!e.all_frames);assert(fs.readFileSync(path.join(root,'src/service-worker.js'),'utf8').includes('importScripts("focus-core.js", "lock-core.js")'));assert.deepEqual(m.permissions,['storage']);assert.match(m.name,/BiliThrottle/);});
