'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const f=require('../src/focus-core.js');
const T0=new Date(2026,9,8,20,0,0).getTime();
const on=(x={})=>f.settings({focusEnabled:true,...x});
function watch(u,s,seconds,id,start=T0){let now=start;for(let i=0;i<seconds;i+=5){now+=5000;u=f.tick(u,now,s,5,id);}return{u,now};}

test('focus mode is off by default and settings are clamped',()=>{const s=f.settings({});assert.equal(s.focusEnabled,false);assert.equal(s.focusDailyMinutes,90);const c=f.settings({focusDailyMinutes:-5,focusBreakMinutes:0,focusResetHour:99,focusDailyVideos:'x'});assert.equal(c.focusDailyMinutes,0);assert.equal(c.focusBreakMinutes,1);assert.equal(c.focusResetHour,12);assert.equal(c.focusDailyVideos,0);});
test('disabled focus mode never blocks',()=>{const s=f.settings({focusDailyMinutes:1});const {u,now}=watch(null,s,120,'BV1xx411c7mD');assert.equal(f.evaluate(u,now,s,'BV1xx411c7mD').block,null);});
test('daily time limit blocks once reached',()=>{const s=on({focusDailyMinutes:1,focusSessionMinutes:0});let r=watch(null,s,55,'BV1xx411c7mD');assert.equal(f.evaluate(r.u,r.now,s).block,null);r=watch(r.u,s,5,'BV1xx411c7mD',r.now);assert.equal(f.evaluate(r.u,r.now,s).block.kind,'time');});
test('day key honours the reset hour',()=>{assert.equal(f.dayKey(new Date(2026,9,9,3,0).getTime(),4),'2026-10-08');assert.equal(f.dayKey(new Date(2026,9,9,5,0).getTime(),4),'2026-10-09');assert.equal(f.dayKey(new Date(2026,9,9,3,0).getTime(),0),'2026-10-09');});
test('usage resets on a new day',()=>{const s=on({focusDailyMinutes:1});const r=watch(null,s,60,'BV1xx411c7mD');const next=f.usage(r.u,T0+86400000,s);assert.equal(next.seconds,0);assert.equal(f.evaluate(next,T0+86400000,s).block,null);});
test('video counts after 10 seconds; current video may finish, new one is blocked',()=>{const s=on({focusDailyMinutes:0,focusDailyVideos:2,focusSessionMinutes:0});let r=watch(null,s,5,'BV1aa411c7mD');assert.equal(r.u.videos.length,0);r=watch(r.u,s,10,'BV1aa411c7mD',r.now);assert.equal(r.u.videos.length,1);r=watch(r.u,s,15,'BV1bb411c7mD',r.now);assert.equal(r.u.videos.length,2);assert.equal(f.evaluate(r.u,r.now,s,'BV1bb411c7mD').block,null);assert.equal(f.evaluate(r.u,r.now,s,'BV1cc411c7mD').block.kind,'videos');});
test('pomodoro break starts after a continuous session and ends by itself',()=>{const s=on({focusDailyMinutes:0,focusSessionMinutes:1,focusBreakMinutes:2});const r=watch(null,s,60,'BV1aa411c7mD');const e=f.evaluate(r.u,r.now,s);assert.equal(e.block.kind,'break');const during=f.tick(r.u,r.now+5000,s,5,'BV1aa411c7mD');assert.equal(during.seconds,r.u.seconds,'no counting during a break');const after=f.usage(r.u,r.now+121000,s);const t=f.tick(after,r.now+121000,s,5,'BV1aa411c7mD');assert.equal(f.evaluate(t,r.now+121000,s).block,null);assert.equal(t.sessionSeconds,5);});
test('a long pause resets the pomodoro session',()=>{const s=on({focusDailyMinutes:0,focusSessionMinutes:10,focusBreakMinutes:5});const r=watch(null,s,300,'BV1aa411c7mD');const t=f.tick(r.u,r.now+6*60000,s,5,'BV1aa411c7mD');assert.equal(t.sessionSeconds,5);assert.equal(t.seconds,305);});
test('snooze grants five minutes / one video / skips break, but never in strict mode',()=>{const s=on({focusDailyMinutes:1,focusSessionMinutes:0});const r=watch(null,s,60,'BV1aa411c7mD');const sn=f.snooze(r.u,r.now,s,'time');assert.equal(f.evaluate(sn,r.now,s).block,null);assert.equal(f.evaluate(sn,r.now,s).remaining,300);assert.equal(sn.snoozes,1);const strict={...s,focusStrict:true};assert.equal(f.evaluate(f.snooze(r.u,r.now,strict,'time'),r.now,strict).block.kind,'time');
 const b=on({focusDailyMinutes:0,focusSessionMinutes:1});const rb=watch(null,b,60,'BV1aa411c7mD');assert.equal(f.evaluate(f.snooze(rb.u,rb.now,b,'break'),rb.now,b).block,null);});
test('tick input is bounded and corrupt storage is ignored',()=>{const s=on();const u=f.tick({day:f.dayKey(T0,4),seconds:'NaN',videos:'x',breakUntil:T0+999*3600000},T0,s,9999,'BV1aa411c7mD');assert.equal(u.seconds,30);assert.equal(u.breakUntil,0);assert.deepEqual(u.videos,['BV1aa411c7mD'],'30 bounded seconds count the video');});
test('video ids for normal, multi-part, bangumi and live pages',()=>{assert.equal(f.videoId('https://www.bilibili.com/video/BV1xx411c7mD/?p=2'),'BV1xx411c7mD');assert.equal(f.videoId('https://www.bilibili.com/bangumi/play/ep123'),'ep123');assert.equal(f.videoId('https://live.bilibili.com/21452505?x=1'),'live21452505');assert.equal(f.videoId('https://www.bilibili.com/'),null);assert.equal(f.videoId('https://search.bilibili.com/all?keyword=a'),null);});
test('focus scripts are declared in the manifest and the service worker loads the core',()=>{const root=path.join(__dirname,'..');const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));const e=m.content_scripts.find(c=>c.js.includes('src/focus-guard.js'));assert.deepEqual(e.js,['src/focus-core.js','src/focus-guard.js']);assert.equal(e.world,'ISOLATED');assert(!e.all_frames);assert(fs.readFileSync(path.join(root,'src/service-worker.js'),'utf8').includes('importScripts("focus-core.js")'));assert.deepEqual(m.permissions,['storage']);});
