'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const home=require('../src/home-core.js'),diagnostics=require('../src/diagnostics-core.js');
const root=path.join(__dirname,'..');
function auto(){
 let time=5000;
 const c=vm.createContext({console,URL,Headers,Response,Request,AbortController,DOMException,Uint8Array,ArrayBuffer,performance,setTimeout,clearTimeout,WeakRef});
 for(const f of ['range-core.js','flow-policy.js','cdn-resolver.js','idm-downloader.js'])vm.runInContext(fs.readFileSync(path.join(root,'src',f),'utf8'),c,{filename:f});
 const a=c.__BILI_IDM_DOWNLOADER_FACTORY__.createAutoConcurrency({now:()=>time});
 return {a,c,advance:ms=>{time+=ms;},feed:(ahead,ms)=>{for(let t=0;t<ms;t+=250){time+=250;a.activity();a.buffer(ahead,true);}}};
}
test('upstream startup starts at16 then returns16->12->8 after15s ahead with cooldown',()=>{const x=auto();x.a.newSession();assert.equal(x.a.threads(),16);assert.equal(x.a.status().startup.base,8);x.feed(9,4000);assert.equal(x.a.threads(),16);x.feed(16,250);assert.equal(x.a.threads(),12);x.feed(16,1000);assert.equal(x.a.threads(),12);x.feed(16,2000);assert.equal(x.a.threads(),8);assert.equal(x.a.status().startup,null);});
test('startup never climbs past a429-refused level',()=>{const x=auto();x.a.stall();assert.equal(x.a.threads(),12);x.a.pushback(429);assert.equal(x.a.threads(),8);x.a.newSession();assert.equal(x.a.threads(),8);assert.equal(x.a.status().startup,null);});
test('startup pressure climbs to24 and cancels startup reduction',()=>{const x=auto();x.a.newSession();assert.equal(x.a.stall(),false);x.advance(2600);assert.equal(x.a.stall(),true);assert.equal(x.a.threads(),24);assert.equal(x.a.status().startup,null);x.feed(20,5000);assert.equal(x.a.threads(),24);});
test('startup expires after30 seconds without being mistaken for successful buffering',()=>{const x=auto();x.a.newSession();for(let i=0;i<125;i++){x.advance(250);x.a.activity();x.a.buffer(6+i*.02,true);}assert.equal(x.a.threads(),16);assert.equal(x.a.status().startup,null);});
test('seek during startup retains original base level',()=>{const x=auto();x.a.newSession();x.advance(1000);x.a.newSession();assert.equal(x.a.status().startup.base,8);x.feed(20,6000);assert.equal(x.a.threads(),8);});
test('auto reset clears startup state',()=>{const x=auto();x.a.newSession();x.a.reset();assert.equal(x.a.threads(),8);assert.equal(x.a.status().startup,null);});
test('Flow economy cap still wins over upstream startup controller',()=>{const x=auto(),factory=x.c.__BILI_IDM_DOWNLOADER_FACTORY__;factory.autoConcurrency.newSession();const d=factory.createDownloader({nativeFetch:()=>{},getSettings:()=>({autoConcurrency:true,strategy:'economy'})});assert.equal(d.getConcurrency(),4);});
test('home defaults preserve native theme and seasonal banner; remove carousel',()=>{assert.equal(home.defaults.homeTheme,'native');assert.equal(home.defaults.homeHideBanner,false);assert.equal(home.defaults.homeHideCarousel,true);});
test('all1.0 custom themes migrate to native without changing explicit master/history off',()=>{for(const old of ['light','dark','auto','off',null]){const s=home.settings({homeTheme:old,homeEnabled:false,homeHistory:false});assert.equal(s.homeTheme,'native');assert.equal(s.homeEnabled,false);assert.equal(s.homeHistory,false);}assert.equal(home.settings({homeTheme:'oled'}).homeTheme,'oled');});
test('history rejects URL credentials, nonstandard port, javascript and foreign hosts',()=>{for(const url of ['https://u:p@www.bilibili.com/video/BV1foo','https://www.bilibili.com:444/video/BV1foo','javascript:alert(1)','https://evil.test/video/BV1foo'])assert.equal(home.card({url,title:'x'}),null);});
test('history canonicalizes trailing slash and strips cover query tokens',()=>{const a=home.card({url:'/video/BV1foo/?spm=secret',title:'x',image:'https://i0.hdslb.com/bfs/x.jpg?token=secret#x'});assert.equal(a.url,'https://www.bilibili.com/video/BV1foo');assert.equal(a.image,'https://i0.hdslb.com/bfs/x.jpg');});
test('batch identity includes cards beyond first12, fixing old snapshot collision',()=>{const a=Array.from({length:15},(_,i)=>({url:`/video/BV1foo${i}`,title:'x'}));let h=home.append([],a);const b=a.slice();b[14]={url:'/video/BV1different',title:'x'};h=home.append(h,b);assert.equal(h.length,2);});
test('lazy growth is distinct from replacement or reorder',()=>{const a=home.cards([{url:'/video/BV1a',title:'a'},{url:'/video/BV1b',title:'b'}]);const b=home.cards([...a,{url:'/video/BV1c',title:'c'}]);assert(home.grows(a,b));assert(!home.grows(a,b.slice().reverse()));assert(!home.grows(a,b.slice(1)));});
test('future-dated and expired batches are discarded and card budget enforced',()=>{const a=Array.from({length:80},(_,i)=>({url:`/video/BV1f${i}`,title:'x'}));const now=Date.now();assert.equal(home.cards(a).length,36);assert.equal(home.history([{at:now+120000,cards:a},{at:now-home.TTL,cards:a}],now).length,0);});
test('diagnostics redact media URLs, ordinary query strings, fragments and JSON credentials',()=>{const s=diagnostics.redact('{"cookie":"session-secret","url":"https://upos.example.bilivideo.com/a.m4s?upsig=secret", "page":"https://www.bilibili.com/video/BV1test?token=secret#ref", "token":"abc"}');assert(!s.includes('session-secret'));assert(!s.includes('upsig'));assert(!s.includes('a.m4s'));assert(!s.includes('?'));assert(!s.includes('#ref'));assert(s.includes('https://www.bilibili.com/video/BV1test'));assert(!s.includes('abc'));});
test('all runtime version identifiers use the fork release version',()=>{const s=fs.readFileSync(path.join(root,'src/page-hook.js'),'utf8');assert(s.includes('version: "2.5.0"'));assert(!s.includes('version: "1.0.0"'));});
test('MV3 bundles one copy of every runtime dependency, has no remotely hosted executable code',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));assert.equal(m.version,'2.5.0');assert(!m.update_url);for(const entry of m.content_scripts){assert.equal(new Set(entry.js).size,entry.js.length);if(entry.js.includes('src/settings-panel.js'))assert(entry.js.indexOf('src/diagnostics-core.js')<entry.js.indexOf('src/settings-panel.js'));if(entry.js.includes('src/home-enhancer.js'))assert.equal(entry.run_at,'document_start');}assert(!fs.readFileSync(path.join(root,'src/home-enhancer.js'),'utf8').includes('location.reload('));});
function nativeHarness(){
 let active=false,seq=0;
 class MemoryStorage{constructor(){this.data=new Map();}getItem(k){return this.data.get(String(k))??null;}setItem(k,v){this.data.set(String(k),String(v));}removeItem(k){this.data.delete(String(k));}}
 class Source extends EventTarget{constructor(){super();this.readyState='open';this.sourceBuffers=new EventTarget();this.sourceBuffers.length=0;}static isTypeSupported(mime){return !mime.includes('unsupported');}}
 class LocalURL extends URL{static createObjectURL(){return 'blob:fixture/'+(++seq);}}
 const storage=new MemoryStorage();storage.setItem('enableHEVCError','old-false-negative');storage.setItem('my-preference','keep');
 const c=vm.createContext({console,URL:LocalURL,MediaSource:Source,Storage:MemoryStorage,localStorage:storage,sessionStorage:new MemoryStorage(),document:{querySelector:()=>active?{}:null},setTimeout,clearTimeout,performance,DOMException,
 __BILI_RANGE_CORE__:{},__BILI_SIDX__:{},__BILI_CDN_RESOLVER_FACTORY__:{},__BILI_IDM_DOWNLOADER_FACTORY__:{}});
 let source=fs.readFileSync(path.join(root,'src/native-mse-player.js'),'utf8');
 // Test-only access to private state; shipped source is not modified.
 source=source.replace('  root.__BILI_NATIVE_MSE_PLAYER_FACTORY__ =','  root.__fixture = {nativeSourceSettled,pageMediaSources,codecFailures};\n  root.__BILI_NATIVE_MSE_PLAYER_FACTORY__ =');
 vm.runInContext(source,c);return {c,Source,storage,active:v=>{active=v;}};
}
test('codec cleanup removes only five known flags and runs once per origin',()=>{const x=nativeHarness();assert.equal(x.storage.getItem('enableHEVCError'),null);assert.equal(x.storage.getItem('my-preference'),'keep');assert.equal(x.storage.getItem('BTR.codecFailuresCleared'),'1');});
test('codec flag guard applies only while BTR takeover is active; unrelated writes remain valid',()=>{const x=nativeHarness();x.storage.setItem('decodeAV1Error','real');assert.equal(x.storage.getItem('decodeAV1Error'),'real');x.active(true);x.storage.setItem('decodeAV1Error','takeover-race');assert.equal(x.storage.getItem('decodeAV1Error'),'real');x.storage.setItem('ordinary-setting','saved');assert.equal(x.storage.getItem('ordinary-setting'),'saved');assert.equal(x.c.__fixture.codecFailures.blocked,1);x.active(false);x.storage.setItem('decodeAV1Error','native');assert.equal(x.storage.getItem('decodeAV1Error'),'native');});
test('native source wait observes source-buffer creation before takeover',async()=>{const x=nativeHarness(),source=new x.Source(),url=x.c.URL.createObjectURL(source);let done=false;const waiting=x.c.__fixture.nativeSourceSettled({src:url}).then(()=>{done=true;});source.sourceBuffers.length=1;source.sourceBuffers.dispatchEvent(new Event('addsourcebuffer'));await new Promise(r=>setTimeout(r,30));assert.equal(done,false);source.sourceBuffers.length=2;source.sourceBuffers.dispatchEvent(new Event('addsourcebuffer'));await waiting;assert(done);});
test('native source wait has a one-second upper bound when no buffers arrive',async()=>{const x=nativeHarness(),s=new x.Source(),url=x.c.URL.createObjectURL(s),start=performance.now();await x.c.__fixture.nativeSourceSettled({src:url});const elapsed=performance.now()-start;assert(elapsed>=900&&elapsed<2500,elapsed);});
test('native media source registry stays bounded and settled/closed sources do not wait',()=>{const x=nativeHarness();for(let i=0;i<24;i++)x.c.URL.createObjectURL(new x.Source());assert.equal(x.c.__fixture.pageMediaSources.size,16);const s=new x.Source(),url=x.c.URL.createObjectURL(s);s.sourceBuffers.length=2;assert.equal(x.c.__fixture.nativeSourceSettled({src:url}),null);s.sourceBuffers.length=0;s.readyState='closed';assert.equal(x.c.__fixture.nativeSourceSettled({src:url}),null);});
test('native HiRes and Dolby preferences are honored only when codec support is reported',()=>{const x=nativeHarness(),select=x.c.__BILI_NATIVE_MSE_PLAYER_FACTORY__.selectRepresentations;const p={data:{quality:80,dash:{video:[{id:80,height:1080,codecs:'avc1.64001f'}],audio:[{id:1,codecs:'mp4a.40.2'}],flac:{audio:{id:2,codecs:'fLaC'}},dolby:{audio:[{id:3,codecs:'ec-3'}]}}}};assert.equal(select(p,80,'',0).audio.id,1);assert.equal(select(p,80,'',2).audio.id,2);assert.equal(select(p,80,'',1).audio.id,3);p.data.dash.flac.audio.codecs='unsupported';assert.equal(select(p,80,'',2).audio.id,1);});
